import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../transactions/domain/entities/transaction_entity.dart';
import '../../../transactions/domain/entities/transaction_item_entity.dart';
import '../../../transactions/domain/repositories/transaction_repository.dart';
import '../../presentation/models/cart_state.dart';
import '../../../../core/di/providers.dart';

// Provider for UseCase
final confirmPaymentUseCaseProvider = Provider<ConfirmPaymentUseCase>((ref) {
  final repository = ref.read(transactionRepositoryProvider);
  return ConfirmPaymentUseCase(repository);
});

class ConfirmPaymentUseCase {
  final TransactionRepository _repository;

  ConfirmPaymentUseCase(this._repository);

  Future<TransactionEntity> execute({
    required CartState cart,
    required String paymentMethod,
    required double paidAmount,
  }) async {
    if (cart.items.isEmpty) {
      throw Exception('Keranjang kosong, tidak dapat memproses pembayaran.');
    }

    final now = DateTime.now();
    final invoiceDate = '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}';

    // 1. Fetch Today Transaction Counts for Suffix XXXX
    final startOfDay = DateTime(now.year, now.month, now.day);
    final endOfDay = DateTime(now.year, now.month, now.day, 23, 59, 59, 999);

    final todayTransactions = await _repository.getTransactions(
      startDate: startOfDay,
      endDate: endOfDay,
    );

    // TODO(Sprint 4): Add mutex/lock untuk multi-kasir
    // Race condition sangat jarang di single-kasir MVP
    final countSuffix = (todayTransactions.length + 1).toString().padLeft(4, '0');
    final invoiceNo = 'INV-$invoiceDate-$countSuffix';

    // 2. Map Cart Items to TransactionItemEntity
    final items = cart.items.map((item) => TransactionItemEntity(
      id: 0, // Generated by SQLite
      transactionId: 0, // Generated by SQLite
      productId: item.product.id,
      qty: item.qty,
      unitPrice: item.product.price,
      subtotal: item.subtotal,
      discount: 0.0, // DEC-002: Disabled Sprint 1-2
      product: item.product,
    )).toList();

    // 3. Create Transaction Header Entity
    final transaction = TransactionEntity(
      id: 0, // Generated by SQLite
      invoiceNo: invoiceNo,
      total: cart.grandTotal,
      paidAmount: paidAmount,
      changeAmount: paidAmount - cart.grandTotal,
      paymentMethod: paymentMethod,
      cashierId: 1, // DEC-001: Default Admin Sprint 1-2
      createdAt: now,
      items: items,
      isPrinted: 0, // DEC-006: Default unprinted
      discount: 0.0, // DEC-002
      tax: 0.0, // DEC-003
    );

    // 4. Save via Repository
    return await _repository.saveTransaction(transaction);
  }
}
